In [ ]:
import os

In [ ]:
!pip install transformers

In [ ]:
import torch

In [ ]:
from transformers import BertTokenizer, BertModel

In [ ]:
import random

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
random_seed = 42

In [ ]:
random.seed(random_seed)

In [ ]:
torch.manual_seed(random_seed)

In [ ]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(random_seed)

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [ ]:
model = BertModel.from_pretrained('bert-base-uncased')

In [ ]:
text = " Inueron is for the best AI courses and Harish follows the courses regularly."

In [ ]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [ ]:
encoding = tokenizer.batch_encode_plus([text],padding= True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [ ]:
input_ids = encoding["input_ids"]

In [ ]:
input_ids

tensor([[  101,  1999, 13094,  2239,  2003,  2005,  1996,  2190,  9932,  5352,
          1998, 21291,  4095,  4076,  1996,  5352,  5570,  1012,   102]])

In [ ]:
attention_mask = encoding["attention_mask"]

In [ ]:
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
with torch.no_grad():
  outputs = model(input_ids, attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [ ]:
word_embeddings.shape

torch.Size([1, 19, 768])

In [ ]:
word_embeddings

tensor([[[-0.4599, -0.1590,  0.2565,  ..., -0.2751,  0.7431,  0.4114],
         [-0.3782, -0.7932, -0.7364,  ...,  0.4119,  0.9228,  0.8350],
         [-0.5440, -0.5733,  0.6042,  ..., -0.1234,  0.4746,  0.0597],
         ...,
         [ 0.1671, -0.1344,  0.8274,  ...,  0.1005,  0.6167, -0.4623],
         [ 0.5261,  0.0353,  0.1647,  ..., -0.0641, -0.0410, -0.3867],
         [-0.2013,  0.3354,  0.3465,  ...,  0.6167, -0.0510, -0.6806]]])

In [ ]:
input_ids[0]

tensor(101)

In [ ]:
decode = tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [ ]:
decode

'inueron is for the best ai courses and harish follows the courses regularly.'